In [1]:
import numpy as np

Координаты потребителя

In [2]:
x=-730000.0
y=-5440000.0
z=3230000.0

Координаты первого спутника

In [3]:
x1=15524471.175
y1=-16649826.222
z1=13512272.387

Координаты второго спутника

In [4]:
x2=-2304058.534
y2=-23287906.465
z2=11917038.105

Координаты третьего спутника

In [5]:
x3=16680243.357
y3=-3069625.561
z3=20378551.047

Координаты четвертого спутника

In [6]:
x4=-14799931.395
y4=-21425358.24
z4=6069947.224

In [7]:
r1=np.sqrt((x1-x)**2 + (y1-y)**2 + (z1-z)**2)
r2=np.sqrt((x2-x)**2 + (y2-y)**2 + (z2-z)**2)
r3=np.sqrt((x3-x)**2 + (y3-y)**2 + (z3-z)**2)
r4=np.sqrt((x4-x)**2 + (y4-y)**2 + (z4-z)**2)

Создаем диагональную матрицу 4*4, можно единичную или нулевую матрицу

In [8]:
A=np.eye(4)

In [9]:
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
A[0,0]=(x1-x)/r1
A[0,1]=(y1-y)/r1
A[0,2]=(z1-z)/r1
A[0,3]=1

A[1,0]=(x2-x)/r2
A[1,1]=(y2-y)/r2
A[1,2]=(z2-z)/r2
A[1,3]=1

A[2,0]=(x3-x)/r3
A[2,1]=(y3-y)/r3
A[2,2]=(z3-z)/r3
A[2,3]=1

A[3,0]=(x4-x)/r4
A[3,1]=(y4-y)/r4
A[3,2]=(z4-z)/r4
A[3,3]=1

In [11]:
A

array([[ 0.73014681, -0.50354261,  0.46187712,  1.        ],
       [-0.07905052, -0.8963366 ,  0.43627023,  1.        ],
       [ 0.70911279,  0.09654448,  0.69845416,  1.        ],
       [-0.65490442, -0.74406061,  0.13218927,  1.        ]])

In [12]:
A.T

array([[ 0.73014681, -0.07905052,  0.70911279, -0.65490442],
       [-0.50354261, -0.8963366 ,  0.09654448, -0.74406061],
       [ 0.46187712,  0.43627023,  0.69845416,  0.13218927],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [13]:
Q=np.linalg.inv((A.T.dot(A)))

In [14]:
A.T.dot(A)

array([[ 1.4711041 ,  0.25894535,  0.71146216,  0.70530466],
       [ 0.25894535,  1.6199215 , -0.65454472, -2.04739535],
       [ 0.71146216, -0.65454472,  0.9089744 ,  1.72879078],
       [ 0.70530466, -2.04739535,  1.72879078,  4.        ]])

In [15]:
Q

array([[  3.14598646,  -0.52936065,  -7.15303738,   2.26585391],
       [ -0.52936065,   4.1865101 ,  -4.62958998,   4.23709858],
       [ -7.15303738,  -4.62958998,  30.74880526, -14.39794537],
       [  2.26585391,   4.23709858, -14.39794537,   8.24198346]])

In [16]:
VDOP=np.sqrt(Q[2,2])

In [17]:
HDOP=np.sqrt(Q[0,0]+Q[1,1])

In [18]:
TDOP=np.sqrt(Q[3,3])

In [19]:
PDOP=np.sqrt(Q[0,0]+Q[1,1]+Q[2,2])

In [20]:
GDOP=np.sqrt(TDOP**2 + PDOP**2)

In [21]:
print("VDOP", VDOP)
print("HDOP", HDOP)
print("TDOP", TDOP)
print("PDOP", PDOP)
print("GDOP", GDOP)

VDOP 5.545160525841456
HDOP 2.7078582979270984
TDOP 2.8708854835566564
PDOP 6.171004927805757
GDOP 6.806121162505063
